name: SCP files to server on push
on: [push]
jobs:
  deploy:
    name: "Deploy on push"
    runs-on: ubuntu-latest
    steps:
      - name: SCP given file
        run: |
        scp index.html ${{ secrets.USER }}@${{ secrets.HOST_AND_LOCATION }}
        ${{ secrets.PASSWORD }}

      - name: Test
        run: echo 'Mobile banana'